### ISSUE TITLE
The tool's mining level is incorrect

### ISSUE THREAD

**Issue by eyeofflame** [wendall911/SurvivalistEssentials#9]
With the addition of this mod, iron-level pickaxes can mine obsidian and drop drops normally

**Comment by eyeofflame** [comment]
The game version is 1.19.2，only this mod and tconstruct have been added

**Comment by wendall911** [comment]
Thanks for reporting, not sure what the issue is. I'll let you know what I figure out.

**Comment by wendall911** [comment]
So, it sounds like you downloaded the Official Tinkers' Survival Modpack and are trying to modify it ... it has some datapack overrides that change the harvest level of materials (for progression reasons). I cannot reproduce this in any build, and only know of the override that exists in our modpack. If you look at the book, this is expected behavior.
